/*
 * generated by Xtext 2.24.0
 */
package org.ldbcouncil.pgq.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SqlPgqUiModule extends AbstractSqlPgqUiModule {

	public SqlPgqUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
