/*
 * generated by Xtext 2.24.0
 */
package org.ldbcouncil.pgq;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SqlPgqStandaloneSetup extends SqlPgqStandaloneSetupGenerated {

	public static void doSetup() {
		new SqlPgqStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
