/*
 * generated by Xtext 2.24.0
 */
package org.ldbcouncil.pgq.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.ldbcouncil.pgq.SqlPgqRuntimeModule;
import org.ldbcouncil.pgq.SqlPgqStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SqlPgqIdeSetup extends SqlPgqStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SqlPgqRuntimeModule(), new SqlPgqIdeModule()));
	}
	
}
